compressionLevel: mixed

enableGlobalCache: false

enableHardenedMode: true

nodeLinker: node-modules

packageExtensions:
  styled-components@*:
    peerDependenciesMeta:
      react-is:
        optional: true

yarnPath: .yarn/releases/yarn-4.1.0.cjs
